openapi: 3.0.0
info:
  title: LOCAL MUSIC MANAGER - API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Playlists
  - name: Local Files
  - name: Songs
  - name: Auth
paths:
  /api/v1/playlists:
    get:
      tags:
        - Playlists
      summary: Get Playlists
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Playlists
      summary: Create Playlist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Global Music
                description: ''
                privacyStatus: PRIVATE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/playlists/{id}:
    get:
      tags:
        - Playlists
      summary: Get Playlist
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: PLmdUBVgDeFM0YbishmMv1yOAaeFJDphhD
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/playlists/songs/{id}:
    get:
      tags:
        - Playlists
      summary: Get Playlist Songs
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: PLmdUBVgDeFM0YbishmMv1yOAaeFJDphhD
        - name: only_songs
          in: query
          schema:
            type: boolean
          required: false
          example: true
        - name: include_id
          in: query
          schema:
            type: boolean
          required: false
          example: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: 
              schema:
                oneOf:
                  - type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: HKNqyiV38ss
                        title:
                          type: string
                          example: Addicted To You
                        artists:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                example: Avicci
                              id:
                                type: string
                                example: UCoSqQhr7x3sMUmrEwwdUU_A
                        duration:
                          type: string
                          example: "2:40"
                        setVideoId: 
                          type: string
                          example: 532BB0B422FBC7EC
                        thumbnails:
                          type: array
                          items:
                            type: object
                            properties:
                              url:
                                type: string
                                example: https://i.ytimg.com/vi/HKNqyiV38ss/mqdefault.jpg
                              height:
                                type: integer
                                example: 180
                              width:
                                type: integer
                                example: 320
                  - type: array
                    items:
                      type: string
                      example: Addicted To You - Avicci
    delete:
      tags:
        - Playlists
      summary: Delete songs from playlist
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: PLmdUBVgDeFM0YbishmMv1yOAaeFJDphhD
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                songs:
                  type: array
                  items:
                    type: object
                    properties:
                      videoId:
                        type: string
                        example: HKNqyiV38ss
                      setVideoId:
                        type: string
                        example: 4716165A37EB7BE7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/local-files:
    get:
      tags:
        - Local Files
      summary: Get Local Files
      parameters:
        - name: directory
          in: query
          description: Directory path to search files in url encoded format
          schema:
            type: string
          example: D%3A%5CMusic%5CElectr%C3%B3nic
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/songs/search-songs:
    post:
      tags:
        - Songs
      summary: Search songs based on the search of local-files endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                songs:
                  - identifier: 24
                    title: Addicted To You
                    artist: Avicci
                    originalName: Avicii - Addicted To You.mp3
                    completePath: >-
                      D:\Music\Electronic\Avicii - Addicted To You.mp3
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/songs/{songId}:
    get:
      parameters:
        - name: songId
          in: path
          schema:
            type: string
          required: true
          example: HKNqyiV38ss
      tags:
        - Songs
      summary: Get song
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/songs/save-songs:
    post:
      tags:
        - Songs
      summary: Save Songs to Playlist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                playlist_id: PLmdUBVgDeFx0YbishmMv1yOAaeFJDphhD
                enable_duplicates: false
                songs:
                  - HKNqyiV38ss
                  - '-kBrnF-9d3M'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/configure:
    post:
      tags:
        - Auth
      summary: Configure the project with the Google OAuth Credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: '1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com'
                client_secret: 'abcdefghijklmnopqrstuvwxyz'
                project_id: 'local-music-manager'
                redirect_uri: 'https://davidgarzonv.github.io/local-music-manager-auth'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Get Auth url
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/session:
    post:
      tags:
        - Auth
      summary: Create session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                code: >-
                  4/0AfJohXltht-sTssZCqIAwnB9jXKxA4bcsFtTsN6nQrvA9_LvFDdqmLjVhbEpNh4gyZVOEQ
                state: >-
                  eyJhbGciOiJIUzI1NiIsInR5cC6DkpXVCJ9.eyJleHAiOjE3Mzg3ODc3MDR9.mJQjd3PfaNb_OCplHfgYIwa-xP8IgiTPnbYwVxVDhk8
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                Success: true
                Response:
                  refresh_token: "1//0gj"
                  expires_in: 3599
  /api/v1/auth/refresh:
    post:
      tags:
        - Auth
      summary: Refresh token
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/check:
    post:
      tags:
        - Auth
      summary: Check auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accessToken: 'eyJhbGciOi'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/logout:
    post:
      tags:
        - Auth
      summary: Logout
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}